#!/bin/sh
#
# Copyright 2014-present Facebook. All Rights Reserved.
#
# This program file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program in a file named COPYING; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#

LOGFILE="/var/log/mTerm_$1.log"

if [ "$1" == "KDB_A" ] || [ "$1" == "KDB_B" ] || [ "$1" == "QFDB_A" ] || [ "$1" == "QFDB_B" ] || [ "$1" == "QFDB_C" ] || [ "$1" == "QFDB_D" ]
then
  SLOT=$1
else
  echo "Usage: sol-util [ KDB_A, KDB_B, QFDB_D, QFDB_C, QFDB_B, QFDB_A ]"
  echo "       sol-util [ KDB_A, KDB_B, QFDB_D, QFDB_C, QFDB_B, QFDB_A ] --history"
  exit -1
fi

if [ $# -gt 1 ]; then
  if [[ "$2" == "--history" ]]; then
    cat $LOGFILE 2>/dev/null
    exit 0
  fi
fi

exec /usr/local/bin/mTerm_client ${SLOT}_2

echo
echo
echo "-----------------------"
echo "Exit from SOL session."
